# Generated by Django 5.0.3 on 2024-11-10 14:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vokr_app', '0002_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=50)),
                ('message', models.TextField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='vokr_app.session')),
            ],
        ),
    ]
