# Generated by Django 5.0.3 on 2024-11-10 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vokr_app', '0003_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sent_at',
            new_name='sent_timestamp',
        ),
    ]
