# Generated by Django 5.0.3 on 2024-11-12 15:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vokr_app', '0004_rename_sent_at_message_sent_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='access_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
